### ISSUE TITLE
Are you sure you copied functions from GML (Graph Modelling Language) and not GLM (OpenGL Mathematics)?

### ISSUE THREAD

**Issue by Sigmarik** [XorDev/GML_Shaders#1]
It seems like repository contains functions from GLM while the repository title and README states they are taken from GML, which is probably not true.

[GML](https://en.wikipedia.org/wiki/Graph_Modelling_Language)

[GLM](https://glm.g-truc.net/0.9.9/index.html)

**Comment by XorDev** [comment]
[GameMaker Langauge](https://manual-en.yoyogames.com/GameMaker_Language.htm)
